name:                getting-wet
version:             0.1.0.0
github:              "jmgimeno/getting-wet"
license:             BSD3
author:              "Juan Manuel Gimeno Illa"
maintainer:          "jmgimeno@gmail.com"
copyright:           "2020 Juan Manuel Gimeno Illa"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/getting-wet#readme>

dependencies:
  - liquid-base
  - liquid-vector
  - liquid-containers
  - liquid-bytestring
  - liquidhaskell

library:
  source-dirs: src
  ghc-options:
  - -fplugin=LiquidHaskell  

